spring:
  application:
    name: Digital Library
  profiles:
    active: default


  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: rani0012
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080